import { useState } from 'react';
import { Send } from 'lucide-react';
type Form = { name: string; email: string; phone: string; topic: string; message: string; privacy: boolean };
const initial: Form = { name:'', email:'', phone:'', topic:'Termin anfragen', message:'', privacy:false };
export function ContactForm() { const [form,setForm]=useState(initial); const [errors,setErrors]=useState<Partial<Record<keyof Form,string>>>({}); const [status,setStatus]=useState<'idle'|'sending'|'success'|'failed'>('idle');
  const update=(k:keyof Form,v:string|boolean)=>{setForm(f=>({...f,[k]:v})); setErrors(e=>({...e,[k]:undefined}));};
  const validate=()=>{const e:Partial<Record<keyof Form,string>>={}; if(!form.name.trim()) e.name='Bitte gib deinen Namen ein.'; if(!/^\S+@\S+\.\S+$/.test(form.email)) e.email='Bitte gib eine gültige E-Mail-Adresse ein.'; if(!form.message.trim()||form.message.trim().length<10) e.message='Bitte beschreibe dein Anliegen mit mindestens 10 Zeichen.'; if(!form.privacy) e.privacy='Bitte stimme der Verarbeitung zur Kontaktaufnahme zu.'; setErrors(e); return !Object.keys(e).length;};
  const submit=async(ev:React.FormEvent)=>{ev.preventDefault(); setStatus('idle'); if(!validate()) return; setStatus('sending'); try { await new Promise(r=>setTimeout(r,700)); /* DEMO-MODUS: Hier später Formspree, Resend oder eigenen API-Endpunkt integrieren. */ setStatus('success'); setForm(initial); } catch { setStatus('failed'); }};
  const field='w-full rounded-sm border border-ink/15 bg-warm-white/80 px-4 py-3 text-base text-ink outline-none transition focus:border-champagne focus:bg-white focus:ring-2 focus:ring-champagne/20';
  return <form id="contact-form" onSubmit={submit} noValidate className="rounded-[1.5rem] border border-ink/10 bg-white/55 p-5 backdrop-blur md:p-8"><div className="grid gap-5 md:grid-cols-2"><label>Name<input className={field} value={form.name} onChange={e=>update('name',e.target.value)} autoComplete="name" />{errors.name&&<span className="error">{errors.name}</span>}</label><label>E-Mail<input className={field} value={form.email} onChange={e=>update('email',e.target.value)} autoComplete="email" />{errors.email&&<span className="error">{errors.email}</span>}</label><label>Telefon <span className="text-ink/45">optional</span><input className={field} value={form.phone} onChange={e=>update('phone',e.target.value)} autoComplete="tel" /></label><label>Anliegen<select className={field} value={form.topic} onChange={e=>update('topic',e.target.value)}>{['Termin anfragen','Beauty-Beratung','Make-up','Styling','Kooperation','Sonstiges'].map(o=><option key={o}>{o}</option>)}</select></label></div><label className="mt-5 block">Nachricht<textarea className={`${field} min-h-36 resize-y`} value={form.message} onChange={e=>update('message',e.target.value)} />{errors.message&&<span className="error">{errors.message}</span>}</label><label className="mt-5 flex gap-3 text-sm leading-6 text-ink/70"><input type="checkbox" checked={form.privacy} onChange={e=>update('privacy',e.target.checked)} className="mt-1 size-4 accent-champagne"/> <span>Ich habe die <a href="#" className="underline">Datenschutzerklärung</a> gelesen und stimme der Verarbeitung meiner Angaben zur Kontaktaufnahme zu.</span></label>{errors.privacy&&<span className="error">{errors.privacy}</span>}<button disabled={status==='sending'} className="mt-7 inline-flex min-h-12 items-center gap-3 rounded-sm bg-ink px-6 py-3 text-sm font-bold uppercase tracking-[.18em] text-warm-white transition hover:bg-champagne disabled:opacity-60">{status==='sending'?'Wird gesendet':'Anfrage senden'}<Send className="size-4"/></button>{status==='success'&&<p className="mt-4 text-sm text-ink">Danke – deine Demo-Anfrage wurde erfolgreich vorbereitet.</p>}{status==='failed'&&<p className="mt-4 text-sm text-red-700">Das hat nicht funktioniert. Bitte versuche es erneut.</p>}</form> }
